"""Abstrações fundamentais compartilhadas pelo domínio."""

from ultrastats_ai.domain.shared.aggregate_root import AggregateRoot
from ultrastats_ai.domain.shared.domain_event import DomainEvent
from ultrastats_ai.domain.shared.entity import Entity
from ultrastats_ai.domain.shared.errors import (
    DomainError,
    DomainValidationError,
    EntityNotFoundError,
    InvariantViolationError,
    ResultAccessError,
)
from ultrastats_ai.domain.shared.identifiers import (
    AliasId,
    BankrollAccountId,
    BankrollTransactionId,
    BetId,
    BettingMarketId,
    BettingSelectionId,
    BookmakerId,
    CanonicalId,
    CityId,
    CoachId,
    CompetitionId,
    CountryId,
    EntityId,
    ExternalIdentityId,
    FeatureSetId,
    MatchEventId,
    MatchId,
    MatchRevisionId,
    OddId,
    PersonId,
    PlayerId,
    PortfolioId,
    PredictionId,
    PredictionModelId,
    ProviderId,
    RecommendationId,
    RefereeId,
    RegionId,
    RoundId,
    SeasonId,
    SquadRegistrationId,
    StageId,
    StatisticalModelId,
    TeamId,
    TeamMembershipId,
    TieId,
    VenueId,
)
from ultrastats_ai.domain.shared.repository import Repository
from ultrastats_ai.domain.shared.result import Result
from ultrastats_ai.domain.shared.text_value import (
    TextValue,
    compile_text_pattern,
)
from ultrastats_ai.domain.shared.value_object import ValueObject

from ultrastats_ai.domain.shared.aliases import AliasValue
from ultrastats_ai.domain.shared.codes import (
    CodeValue,
    CompetitionCode,
    CountryCode,
    OrganizationCode,
)

from ultrastats_ai.domain.shared.geographic import (
    Coordinates,
    Latitude,
    Longitude,
)

from ultrastats_ai.domain.shared.external_ids import (
    ExternalIdentifier,
    ExternalIdentity,
    ProviderNamespace,
)

from ultrastats_ai.domain.shared.numeric import (
    Age,
    DecimalValue,
    Height,
    IntegerValue,
    Money,
    Odds,
    Percentage,
    Position,
    Probability,
    RoundNumber,
    ShirtNumber,
    Weight,
)

from ultrastats_ai.domain.shared.temporal import (
    DomainDate,
    TemporalInterval,
    TimeZone,
    UtcTimestamp,
)

from ultrastats_ai.domain.shared.names import (
    CityName,
    CompetitionName,
    CountryName,
    DisplayName,
    GeographicName,
    Name,
    OrganizationName,
    PersonName,
    ProperName,
    RegionName,
    ShortName,
    VenueName,
)

from ultrastats_ai.domain.shared.slugs import SlugValue

__all__ = [
    "AliasValue",
    "Age",
    "AggregateRoot",
    "AliasId",
    "BankrollAccountId",
    "BankrollTransactionId",
    "BetId",
    "BettingMarketId",
    "BettingSelectionId",
    "BookmakerId",
    "CanonicalId",
    "CityId",
    "CityName",
    "CoachId",
    "CodeValue",
    "CompetitionCode",
    "CountryCode",
    "OrganizationCode",
    "CompetitionId",
    "CompetitionName",
    "Coordinates",
    "CountryId",
    "CountryName",
    "DecimalValue",
    "DomainError",
    "DomainEvent",
    "DomainValidationError",
    "DisplayName",
    "DomainDate",
    "ExternalIdentifier",
    "ExternalIdentity",
    "Entity",
    "EntityId",
    "EntityNotFoundError",
    "ExternalIdentityId",
    "FeatureSetId",
    "GeographicName",
    "Height",
    "IntegerValue",
    "Latitude",
    "Longitude",
    "InvariantViolationError",
    "MatchEventId",
    "MatchId",
    "MatchRevisionId",
    "Money",
    "Name",
    "OddId",
    "Odds",
    "OrganizationName",
    "Percentage",
    "PersonId",
    "PersonName",
    "PlayerId",
    "PortfolioId",
    "Position",
    "PredictionId",
    "PredictionModelId",
    "Probability",
    "ProperName",
    "ProviderNamespace",
    "ProviderId",
    "RecommendationId",
    "RefereeId",
    "RegionId",
    "RegionName",
    "Repository",
    "Result",
    "ResultAccessError",
    "RoundId",
    "RoundNumber",
    "SeasonId",
    "ShirtNumber",
    "ShortName",
    "SlugValue",
    "SquadRegistrationId",
    "StageId",
    "StatisticalModelId",
    "TeamId",
    "TemporalInterval",
    "TimeZone",
    "TeamMembershipId",
    "TextValue",
    "TieId",
    "UtcTimestamp",
    "ValueObject",
    "VenueId",
    "VenueName",
    "Weight",
    "compile_text_pattern",
]