"""Abstrações fundamentais compartilhadas pelo domínio."""

from ultrastats_ai.domain.shared.aggregate_root import AggregateRoot
from ultrastats_ai.domain.shared.city_name import CityName
from ultrastats_ai.domain.shared.country_name import CountryName
from ultrastats_ai.domain.shared.domain_event import DomainEvent
from ultrastats_ai.domain.shared.entity import Entity
from ultrastats_ai.domain.shared.errors import (
    DomainError,
    DomainValidationError,
    EntityNotFoundError,
    InvariantViolationError,
    ResultAccessError,
)
from ultrastats_ai.domain.shared.identifiers import (
    AliasId,
    BankrollAccountId,
    BankrollTransactionId,
    BetId,
    BettingMarketId,
    BettingSelectionId,
    BookmakerId,
    CanonicalId,
    CityId,
    CoachId,
    CompetitionId,
    CountryId,
    EntityId,
    ExternalIdentityId,
    FeatureSetId,
    MatchEventId,
    MatchId,
    MatchRevisionId,
    OddId,
    PersonId,
    PlayerId,
    PortfolioId,
    PredictionId,
    PredictionModelId,
    ProviderId,
    RecommendationId,
    RefereeId,
    RegionId,
    RoundId,
    SeasonId,
    SquadRegistrationId,
    StageId,
    StatisticalModelId,
    TeamId,
    TeamMembershipId,
    TieId,
    VenueId,
)
from ultrastats_ai.domain.shared.display_name import DisplayName
from ultrastats_ai.domain.shared.name import Name
from ultrastats_ai.domain.shared.proper_name import ProperName
from ultrastats_ai.domain.shared.region_name import RegionName
from ultrastats_ai.domain.shared.repository import Repository
from ultrastats_ai.domain.shared.result import Result
from ultrastats_ai.domain.shared.short_name import ShortName
from ultrastats_ai.domain.shared.text_value import (
    TextValue,
    compile_text_pattern,
)
from ultrastats_ai.domain.shared.value_object import ValueObject

__all__ = [
    "AggregateRoot",
    "AliasId",
    "BankrollAccountId",
    "BankrollTransactionId",
    "BetId",
    "BettingMarketId",
    "BettingSelectionId",
    "BookmakerId",
    "CanonicalId",
    "CityId",
    "CityName",
    "CoachId",
    "CompetitionId",
    "CountryId",
    "CountryName",
    "DomainError",
    "DomainEvent",
    "DomainValidationError",
    "DisplayName",
    "Entity",
    "EntityId",
    "EntityNotFoundError",
    "ExternalIdentityId",
    "FeatureSetId",
    "InvariantViolationError",
    "MatchEventId",
    "MatchId",
    "MatchRevisionId",
    "Name",
    "OddId",
    "PersonId",
    "PlayerId",
    "PortfolioId",
    "PredictionId",
    "PredictionModelId",
    "ProperName",
    "ProviderId",
    "RecommendationId",
    "RefereeId",
    "RegionId",
    "RegionName",
    "Repository",
    "Result",
    "ResultAccessError",
    "RoundId",
    "SeasonId",
    "ShortName",
    "SquadRegistrationId",
    "StageId",
    "StatisticalModelId",
    "TeamId",
    "TeamMembershipId",
    "TextValue",
    "TieId",
    "ValueObject",
    "VenueId",
    "compile_text_pattern",
]