"""API pública do Match Context."""

from ultrastats_ai.domain.match.enums import (
    AppointmentStatus,
    DecisionStatus,
    EventStatus,
    InterruptionStatus,
    LineupRole,
    LineupStatus,
    LineupType,
    MatchParticipantStatus,
    MatchType,
    PeriodStatus,
    PeriodType,
    RevisionStatus,
    SquadStatus,
    SquadType,
    StatisticScope,
    StatisticUnit,
    SurfaceCondition,
    SurfaceType,
    VenueRole,
    VenueStatus,
    WeatherCondition,
)
from ultrastats_ai.domain.match.errors import (
    DuplicateMatchParticipantError,
    DuplicateMatchRecordError,
    DuplicateMatchVenueError,
    DuplicateScheduleChangeError,
    InvalidMatchParticipantsError,
    InvalidMatchScheduleError,
    InvalidMatchStatusTransitionError,
    InvalidMatchVenueError,
    InvalidScheduleChangeError,
    MatchDomainError,
    MatchParticipantNotFoundError,
    MatchParticipantOwnershipError,
    MatchRecordOwnershipError,
    MatchVenueOwnershipError,
    MultipleCurrentMatchVenuesError,
    ScheduleChangeOwnershipError,
)
from ultrastats_ai.domain.match.lifecycle import can_transition
from ultrastats_ai.domain.match.match import Match
from ultrastats_ai.domain.match.participant import MatchParticipant
from ultrastats_ai.domain.match.schedule_change import MatchScheduleChange
from ultrastats_ai.domain.match.records import (
    InvalidMatchRecordError,
    Lineup,
    LineupEntry,
    MatchDecision,
    MatchEvent,
    MatchInterruption,
    MatchOfficial,
    MatchPeriod,
    MatchRevision,
    MatchSquad,
    MatchStatistic,
)
from ultrastats_ai.domain.match.venue import MatchVenue

__all__ = [
    "AppointmentStatus",
    "DecisionStatus",
    "DuplicateMatchParticipantError",
    "DuplicateMatchRecordError",
    "DuplicateMatchVenueError",
    "DuplicateScheduleChangeError",
    "EventStatus",
    "InterruptionStatus",
    "InvalidMatchParticipantsError",
    "InvalidMatchRecordError",
    "InvalidMatchScheduleError",
    "InvalidMatchStatusTransitionError",
    "InvalidMatchVenueError",
    "InvalidScheduleChangeError",
    "Match",
    "Lineup",
    "LineupEntry",
    "LineupRole",
    "LineupStatus",
    "LineupType",
    "MatchDecision",
    "MatchDomainError",
    "MatchEvent",
    "MatchInterruption",
    "MatchOfficial",
    "MatchParticipant",
    "MatchParticipantNotFoundError",
    "MatchParticipantOwnershipError",
    "MatchParticipantStatus",
    "MatchPeriod",
    "MatchRecordOwnershipError",
    "MatchRevision",
    "MatchScheduleChange",
    "MatchSquad",
    "MatchStatistic",
    "MatchType",
    "MatchVenue",
    "MatchVenueOwnershipError",
    "MultipleCurrentMatchVenuesError",
    "PeriodStatus",
    "PeriodType",
    "RevisionStatus",
    "ScheduleChangeOwnershipError",
    "SurfaceCondition",
    "SurfaceType",
    "SquadStatus",
    "SquadType",
    "StatisticScope",
    "StatisticUnit",
    "VenueRole",
    "VenueStatus",
    "WeatherCondition",
    "can_transition",
]
