"""create scheduler heartbeat table

Revision ID: 34f16155b3c2
Revises: c7a589aad831
Create Date: 2026-07-16 23:48:31.068886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f16155b3c2'
down_revision: Union[str, Sequence[str], None] = 'c7a589aad831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_job_status', sa.String(length=30), nullable=True),
    sa.Column('last_job_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_job_finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_heartbeats_instance_name'), 'scheduler_heartbeats', ['instance_name'], unique=True)
    op.create_index(op.f('ix_scheduler_heartbeats_last_heartbeat_at'), 'scheduler_heartbeats', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_scheduler_heartbeats_status'), 'scheduler_heartbeats', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_heartbeats_status'), table_name='scheduler_heartbeats')
    op.drop_index(op.f('ix_scheduler_heartbeats_last_heartbeat_at'), table_name='scheduler_heartbeats')
    op.drop_index(op.f('ix_scheduler_heartbeats_instance_name'), table_name='scheduler_heartbeats')
    op.drop_table('scheduler_heartbeats')
    # ### end Alembic commands ###
