"""create sync runs table

Revision ID: c7a589aad831
Revises: cbdce415a7e4
Create Date: 2026-07-16 15:52:10.301528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a589aad831'
down_revision: Union[str, Sequence[str], None] = 'cbdce415a7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('competitions_created', sa.Integer(), nullable=False),
    sa.Column('competitions_updated', sa.Integer(), nullable=False),
    sa.Column('competitions_linked', sa.Integer(), nullable=False),
    sa.Column('teams_created', sa.Integer(), nullable=False),
    sa.Column('teams_updated', sa.Integer(), nullable=False),
    sa.Column('teams_linked', sa.Integer(), nullable=False),
    sa.Column('matches_created', sa.Integer(), nullable=False),
    sa.Column('matches_updated', sa.Integer(), nullable=False),
    sa.Column('matches_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_source'), 'sync_runs', ['source'], unique=False)
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_source'), table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
