"""link bets to bankroll

Revision ID: db33d016d6b4
Revises: 2fbd1f80d28b
Create Date: 2026-07-16 00:55:23.994280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db33d016d6b4'
down_revision: Union[str, Sequence[str], None] = '2fbd1f80d28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('bankroll_id', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('stake_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('bets', sa.Column('payout_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.create_index(op.f('ix_bets_bankroll_id'), 'bets', ['bankroll_id'], unique=False)
    op.create_foreign_key(None, 'bets', 'bankrolls', ['bankroll_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.drop_index(op.f('ix_bets_bankroll_id'), table_name='bets')
    op.drop_column('bets', 'payout_amount')
    op.drop_column('bets', 'stake_amount')
    op.drop_column('bets', 'bankroll_id')
    # ### end Alembic commands ###
