"""create teams table

Revision ID: e39235aeeeb8
Revises: 
Create Date: 2026-07-15 13:46:42.320183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39235aeeeb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('league', sa.String(length=150), nullable=True),
    sa.Column('power_rating', sa.Float(), nullable=False),
    sa.Column('attack_rating', sa.Float(), nullable=False),
    sa.Column('defense_rating', sa.Float(), nullable=False),
    sa.Column('corner_rating', sa.Float(), nullable=False),
    sa.Column('card_rating', sa.Float(), nullable=False),
    sa.Column('goal_rating', sa.Float(), nullable=False),
    sa.Column('offside_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
