"""create bankroll tables

Revision ID: 2fbd1f80d28b
Revises: dde848d5a616
Create Date: 2026-07-16 00:33:56.713376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbd1f80d28b'
down_revision: Union[str, Sequence[str], None] = 'dde848d5a616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankrolls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_percentage', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankrolls_name'), 'bankrolls', ['name'], unique=True)
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bankroll_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bankroll_id'], ['bankrolls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankroll_transactions_bankroll_id'), 'bankroll_transactions', ['bankroll_id'], unique=False)
    op.create_index(op.f('ix_bankroll_transactions_bet_id'), 'bankroll_transactions', ['bet_id'], unique=False)
    op.create_index(op.f('ix_bankroll_transactions_created_at'), 'bankroll_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_bankroll_transactions_transaction_type'), 'bankroll_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankroll_transactions_transaction_type'), table_name='bankroll_transactions')
    op.drop_index(op.f('ix_bankroll_transactions_created_at'), table_name='bankroll_transactions')
    op.drop_index(op.f('ix_bankroll_transactions_bet_id'), table_name='bankroll_transactions')
    op.drop_index(op.f('ix_bankroll_transactions_bankroll_id'), table_name='bankroll_transactions')
    op.drop_table('bankroll_transactions')
    op.drop_index(op.f('ix_bankrolls_name'), table_name='bankrolls')
    op.drop_table('bankrolls')
    # ### end Alembic commands ###
