"""add provider identifiers

Revision ID: cbdce415a7e4
Revises: db33d016d6b4
Create Date: 2026-07-16 14:27:51.542659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdce415a7e4'
down_revision: Union[str, Sequence[str], None] = 'db33d016d6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('competitions', sa.Column('external_id', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=False)
    op.create_index(op.f('ix_competitions_source'), 'competitions', ['source'], unique=False)
    op.add_column('teams', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('external_id', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=False)
    op.create_index(op.f('ix_teams_source'), 'teams', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_source'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_column('teams', 'external_id')
    op.drop_column('teams', 'source')
    op.drop_index(op.f('ix_competitions_source'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.drop_column('competitions', 'external_id')
    op.drop_column('competitions', 'source')
    # ### end Alembic commands ###
