"""create core ultrastats tables

Revision ID: dde848d5a616
Revises: 1652a1208d34
Create Date: 2026-07-15 14:14:58.002203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde848d5a616'
down_revision: Union[str, Sequence[str], None] = '1652a1208d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=30), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_code'), 'markets', ['code'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_competition_id'), 'matches', ['competition_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_at'), 'matches', ['kickoff_at'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('corners_home', sa.Integer(), nullable=True),
    sa.Column('corners_away', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_home', sa.Integer(), nullable=True),
    sa.Column('yellow_cards_away', sa.Integer(), nullable=True),
    sa.Column('red_cards_home', sa.Integer(), nullable=True),
    sa.Column('red_cards_away', sa.Integer(), nullable=True),
    sa.Column('shots_home', sa.Integer(), nullable=True),
    sa.Column('shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_away', sa.Integer(), nullable=True),
    sa.Column('offsides_home', sa.Integer(), nullable=True),
    sa.Column('offsides_away', sa.Integer(), nullable=True),
    sa.Column('possession_home', sa.Float(), nullable=True),
    sa.Column('possession_away', sa.Float(), nullable=True),
    sa.Column('xg_home', sa.Float(), nullable=True),
    sa.Column('xg_away', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_statistics_match_id'), 'match_statistics', ['match_id'], unique=True)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=150), nullable=False),
    sa.Column('odd_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_collected_at'), 'odds', ['collected_at'], unique=False)
    op.create_index(op.f('ix_odds_market_id'), 'odds', ['market_id'], unique=False)
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uqs', sa.Float(), nullable=True),
    sa.Column('use_score', sa.Float(), nullable=True),
    sa.Column('confluence', sa.Float(), nullable=True),
    sa.Column('evidence_level', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_market_id'), 'predictions', ['market_id'], unique=False)
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_match_id'), 'audits', ['match_id'], unique=False)
    op.create_index(op.f('ix_audits_prediction_id'), 'audits', ['prediction_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=150), nullable=False),
    sa.Column('odd_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('profit_units', sa.Float(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_market_id'), 'bets', ['market_id'], unique=False)
    op.create_index(op.f('ix_bets_match_id'), 'bets', ['match_id'], unique=False)
    op.create_index(op.f('ix_bets_prediction_id'), 'bets', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_prediction_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_match_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_market_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_audits_prediction_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_match_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_market_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_market_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_collected_at'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_match_statistics_match_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index(op.f('ix_matches_kickoff_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_competition_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_markets_code'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('competitions')
    # ### end Alembic commands ###
